src/dump.cpp File Reference
#include "tree.h"
#include "utils/html.h"
#include "utils/ptr_valid.h"
#include "log/log.h"
#include "log/dot_log.h"
Macros
#define LOG_(...) log_printf(&log_file, __VA_ARGS__)
#define FPRINTF_(...) if (fprintf(file, __VA_ARGS__) == 0) return TreeNodeActionRes::ERR
#define BACKGROUND_COLOR "\"#1f1f1f\""
#define FONT_COLOR "\"#000000\""
#define NODE_PREFIX "elem_"
#define NODE_PARAMS "shape=\"plaintext\", style=\"filled\", fillcolor=\"#6e7681\""
#define ZERO_NODE_PARAMS "shape=\"plaintext\", style=\"filled\", fillcolor=\"#6e7681\", color=yellow"
#define FPRINTF_(...) if (fprintf(file, __VA_ARGS__) == 0) return false
#define PRINT_ERR_(code, descr)
Functions
void tree_dump (Tree *tree, const VarCodeData call_data)
(Use TREE_DUMP macros) Dumps tree to log file
bool tree_dump_dot (Tree *tree, char *img_filename)
Dumps tree to dot img file.
void tree_print_error (const int err_code)
Prints text error to log file.
Variables
LogFileData log_file
Macro Definition Documentation
BACKGROUND_COLOR
#define BACKGROUND_COLOR "\"#1f1f1f\""
Definition at line 229 of file dump.cpp.
Referenced by tree_dump_dot().
FONT_COLOR
#define FONT_COLOR "\"#000000\""
Definition at line 230 of file dump.cpp.
Referenced by tree_dump_dot().
FPRINTF_ [1/2]
#define FPRINTF_(...) if (fprintf(file, __VA_ARGS__) == 0) return TreeNodeActionRes::ERR
Definition at line 227 of file dump.cpp.
Referenced by tree_dump_dot().
FPRINTF_ [2/2]
#define FPRINTF_(...) if (fprintf(file, __VA_ARGS__) == 0) return false
Definition at line 227 of file dump.cpp.
LOG_
#define LOG_(...) log_printf(&log_file, __VA_ARGS__)
Definition at line 12 of file dump.cpp.
Referenced by tree_dump().
NODE_PARAMS
#define NODE_PARAMS "shape=\"plaintext\", style=\"filled\", fillcolor=\"#6e7681\""
Definition at line 232 of file dump.cpp.
NODE_PREFIX
#define NODE_PREFIX "elem_"
Definition at line 231 of file dump.cpp.
PRINT_ERR_
#define PRINT_ERR_(code, descr)
Value:
                                    if ((err_code) & Tree::code) \
                                    log_printf(&log_file, \
                                               HTML_TEXT(HTML_RED("!!! " #code ": " descr "\n")));
Definition at line 336 of file dump.cpp.
#define PRINT_ERR_(code, descr) if ((err_code) & Tree::code) \
                                    log_printf(&log_file, \
                                               HTML_TEXT(HTML_RED("!!! " #code ": " descr "\n")));
Referenced by tree_print_error().
ZERO_NODE_PARAMS
#define ZERO_NODE_PARAMS "shape=\"plaintext\", style=\"filled\", fillcolor=\"#6e7681\", color=yellow"
Definition at line 233 of file dump.cpp.
Function Documentation
tree_dump()
void tree_dump (Tree * tree, const VarCodeData var_data)
(Use TREE_DUMP macros) Dumps tree to log file
Parameters
tree
var_data
Definition at line 162 of file dump.cpp.
                                                        {
    assert(tree);
    LOG_(HTML_BEGIN);
    LOG_(" tree_dump() called from %s:%d %s\n"
         " %s[%p] initialised in %s:%d %s \n",
         call_data.file, call_data.line, call_data.func,
         tree->var_data.name, tree,
         tree->var_data.file, tree->var_data.line, tree->var_data.func);
    LOG_(" {\n");
    LOG_(" size = %zd\n", tree->size);
    LOG_(" root = %p\n", tree->root);
    LOG_(" {\n");
    if (!is_ptr_valid(tree->root)) {
        if (tree->size != 0 && tree_is_initialised(tree))
            LOG_(HTML_RED(" can't read (invalid pointer)\n"));
        LOG_(" }\n"
             " }\n" HTML_END);
        return;
    }
    LOG_(" "" prefix: ");
    TreeNodeAction* pre_actions[4] = {&tree_dump_log_open_node_val, nullptr,
                                      &tree_dump_log_close_node, &tree_dump_log_nil};
    tree_traversal(tree, &tree->root, pre_actions);
    LOG_("\n");
    LOG_(" "" infix: ");
    TreeNodeAction* in_actions[4] = {&tree_dump_log_open_node, &tree_dump_log_val,
                                     &tree_dump_log_close_node, &tree_dump_log_nil};
    tree_traversal(tree, &tree->root, in_actions);
    LOG_("\n");
    LOG_(" "" postfix: ");
    TreeNodeAction* post_actions[4] = {&tree_dump_log_open_node, nullptr,
                                       &tree_dump_log_close_node_val, &tree_dump_log_nil};
    tree_traversal(tree, &tree->root, post_actions);
    LOG_("\n");
    LOG_(" }\n"
         " }\n" HTML_END);
    char img_filename[log_file.MAX_FILENAME_LEN] = {};
    tree_dump_dot(tree, img_filename);
    LOG_("<img src=\"../../%s\">\n", img_filename);
}
References VarCodeData::file, VarCodeData::func, HTML_BEGIN, HTML_END, HTML_RED, is_ptr_valid(), VarCodeData::line, LOG_, log_file, LogFileData::MAX_FILENAME_LEN, VarCodeData::name, Tree::root, Tree::size, tree_dump_dot(), tree_is_initialised(), tree_traversal(), and Tree::var_data.
tree_dump_dot()
bool tree_dump_dot (Tree * tree, char * img_filename)
Dumps tree to dot img file.
Parameters
tree
img_filename
Returns
true
false
Definition at line 293 of file dump.cpp.
                                                   {
    assert(tree);
    assert(img_filename);
    static size_t dot_number = 0;
    char dot_filename[log_file.MAX_FILENAME_LEN] = {};
    if (snprintf(dot_filename, log_file.MAX_FILENAME_LEN,
                 "%s%zd.dot", log_file.timestamp_dir, dot_number) <= 0)
        return 0;
    FILE* file = fopen(dot_filename, "wb");
    if (file == nullptr)
        return false;
    FPRINTF_("digraph List{\n"
             " graph [bgcolor=" BACKGROUND_COLOR "];\n"
             " node[color=white, fontcolor=" FONT_COLOR ", fontsize=14, "
             "fontname=\"verdana\", style=\"filled\", fillcolor=\"#6e7681\"];\n\n");
    tree_preorder(tree, &tree->root, &tree_dump_dot_log_node_, file);
    FPRINTF_("}\n");
    if (fclose(file) != 0) {
        perror("Error closing file");
        return false;
    }
    if (snprintf(img_filename, log_file.MAX_FILENAME_LEN,
                 "%s%zd.svg", log_file.timestamp_dir, dot_number++) <= 0)
        return false;
    if (!create_img(dot_filename, img_filename)) {
        fprintf(stderr, "Error creating dot graph\n");
        return false;
    }
    return true;
}
References BACKGROUND_COLOR, create_img(), FONT_COLOR, FPRINTF_, log_file, LogFileData::MAX_FILENAME_LEN, Tree::root, LogFileData::timestamp_dir, and tree_preorder().
Referenced by tree_dump().
tree_print_error()
void tree_print_error (const int err_code)
Prints text error to log file.
Parameters
err_code
Definition at line 339 of file dump.cpp.
                                          {
    if (err_code == Tree::OK) {
        log_printf(&log_file, HTML_TEXT(HTML_GREEN("No error\n")));
    } else {
        PRINT_ERR_(ALLOC_ERR, "Can't allocate memory");
        PRINT_ERR_(ALREADY_INITIALISED, "Constructor called for already initialised or corrupted tree");
        PRINT_ERR_(UNITIALISED, "Tree is not initialised");
        PRINT_ERR_(INVALID_NODE_PTR, "TreeNode pointer is not valid for writing");
        PRINT_ERR_(POISON_VAL_FOUND, "There is poison value in TreeNode");
        PRINT_ERR_(INVALID_SIZE, "Actual tree size doesn't equal tree.size");
        PRINT_ERR_(NEGATIVE_SIZE, "Negative tree.size");
        PRINT_ERR_(DAMAGED_PATH, "Tree is damaged. Invalid path");
        PRINT_ERR_(ACTION_ERROR, "Some action on TreeNode failed");
        PRINT_ERR_(NODE_ALREADY_EXISTS, "Insertion is not allowed. Node already exists here");
        PRINT_ERR_(CANNOT_DELETE, "Cannot delete element. It has child/children");
        PRINT_ERR_(NODE_VERIFY_FAIL, "Node elem verification failed");
        PRINT_ERR_(INVALID_ELEM_T_SIZE, "tree.elem_size is <= 0");
    }
}
References HTML_GREEN, HTML_TEXT, log_file, log_printf(), Tree::OK, and PRINT_ERR_.
Variable Documentation
log_file
LogFileData log_file [extern]
Definition at line 4 of file main.cpp.
{"log"};
Referenced by log_close_file(), log_create_timestamp_dir(), log_open_file(), log_printf(), tree_dump(), tree_dump_dot(), and tree_print_error().