src/log/log.h File Reference
#include <stdio.h>
#include <assert.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <dirent.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>
Classes
struct LogFileData
Log file data struct.
Macros
#define WIN(...)
#define UNIX(...) __VA_ARGS__
Functions
int log_printf (LogFileData *log, const char *format,...)
Prints data in printf format to log file.
bool log_open_file (LogFileData *log, const char *mode="ab")
Opens log file.
bool log_close_file (LogFileData *log)
Closes log fle.
bool log_create_dir (const char *dir_name)
Searches for dir by dir_name. If it doesn't exist, creates.
bool log_create_timestamp_dir (LogFileData *log_file)
Creates dir woth timestamp in log_file.dir. Saves it's name to log_file.timestamp_dir.
Macro Definition Documentation
UNIX
#define UNIX(...) __VA_ARGS__
Definition at line 26 of file log.h.
Referenced by log_create_timestamp_dir().
WIN
#define WIN(...)
Definition at line 24 of file log.h.
Referenced by log_create_timestamp_dir().
Function Documentation
log_close_file()
bool log_close_file (LogFileData * log)
Closes log fle.
Parameters
log
Returns
true success
false failure
Definition at line 81 of file log.cpp.
                                           {
    assert(log_file);
    if (log_file->file == nullptr || fclose(log_file->file) != 0) {
        perror("Error closing log_file file");
        return false;
    }
    log_file->file = nullptr;
    return true;
}
References LogFileData::file, and log_file.
Referenced by log_printf().
log_create_dir()
bool log_create_dir (const char * dir_name)
Searches for dir by dir_name. If it doesn't exist, creates.
Parameters
dir_name
Returns
true
false
Definition at line 93 of file log.cpp.
                                          {
    assert(dir_name);
    DIR* dir = opendir(dir_name);
    if (dir) {
        closedir(dir);
    } else if (ENOENT == errno) {
#ifdef _WIN32
        if (CreateDirectoryA(dir_name, NULL) == 0) {
            perror("Error creating dir");
            return false;
        }
#else //< #ifndef _WIN32
        if (mkdir(dir_name, 0744) != 0) {
            perror("Error creating dir");
            return false;
        }
#endif //< #ifdef _WIN32
    } else {
        perror("Error detecting directory");
        return false;
    }
    return true;
}
Referenced by log_create_timestamp_dir(), and log_open_file().
log_create_timestamp_dir()
bool log_create_timestamp_dir (LogFileData * log_file)
Creates dir woth timestamp in log_file.dir. Saves it's name to log_file.timestamp_dir.
Parameters
log_file
Returns
true
false
Definition at line 55 of file log.cpp.
                                                     {
    assert(log_file);
    time_t ltime = time(NULL);
    if (log_file->timestamp_dir[0] == '\0' || ltime - log_file->last_write > log_file->LIFETIME) {
        tm* tm = localtime(&ltime);
        log_file->timestamp_dir[0] = '\0';
        if (snprintf(log_file->timestamp_dir, log_file->MAX_FILENAME_LEN,
                 "%s" UNIX("/") WIN("\\") "%02d-%02d-%04d_%02d-%02d-%02d" UNIX("/") WIN("\\"),
                 log_file->dir, tm->tm_mday, tm->tm_mon + 1, tm->tm_year + 1900,
                                tm->tm_hour, tm->tm_min, tm->tm_sec) <= 0)
            return false;
    }
    log_file->last_write = ltime;
    if (!log_create_dir(log_file->timestamp_dir))
        return false;
    return true;
}
References LogFileData::dir, LogFileData::last_write, LogFileData::LIFETIME, log_create_dir(), log_file, LogFileData::MAX_FILENAME_LEN, LogFileData::timestamp_dir, UNIX, and WIN.
Referenced by log_open_file().
log_open_file()
bool log_open_file (LogFileData * log, const char * mode = "ab")
Opens log file.
Parameters
log
mode fopen() mode
Returns
true success
false failure
Definition at line 31 of file log.cpp.
                                                            {
    assert(log_file);
    if (!log_create_dir(log_file->dir))
        return false;
    if (!log_create_timestamp_dir(log_file))
        return false;
    char filename[LogFileData::MAX_FILENAME_LEN] = {};
    if (snprintf(filename, LogFileData::MAX_FILENAME_LEN, "%slog.html", log_file->timestamp_dir) <= 0)
        return false;
    log_file->file = fopen(filename, mode);
    if (log_file->file == nullptr) {
        perror("Error opening log_file file");
        return false;
    }
    return true;
}
References LogFileData::dir, LogFileData::file, log_create_dir(), log_create_timestamp_dir(), log_file, LogFileData::MAX_FILENAME_LEN, and LogFileData::timestamp_dir.
Referenced by log_printf().
log_printf()
int log_printf (LogFileData * log, const char * format, ...)
Prints data in printf format to log file.
Parameters
log
format
...
Returns
int
Definition at line 3 of file log.cpp.
                                                               {
    assert(log_file);
    assert(format);
    bool file_is_opened_here = false;
    if (log_file->file == nullptr) {
        if (!log_open_file(log_file))
            return -1;
        file_is_opened_here = true;
    }
    va_list arg_list = {};
    va_start(arg_list, format);
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-nonliteral"
    int ret = vfprintf(log_file->file, format, arg_list);
#pragma clang diagnostic pop
    if (file_is_opened_here)
        if (!log_close_file(log_file))
            return -1;
    return ret;
}
References LogFileData::file, log_close_file(), log_file, and log_open_file().
Referenced by tree_print_error().