src/main.cpp File Reference
#include "log/log.h"
#include "tree.h"
Functions
bool int_dtor (void *elem)
bool int_verify (void *elem)
char * int_str (const void *elem)
int main ()
Variables
LogFileData log_file = {"log"}
const int INT_POISON_VAL = __INT_MAX__ - 13
Function Documentation
int_dtor()
bool int_dtor (void * elem) [inline]
Definition at line 8 of file main.cpp.
                                 {
    assert(elem);
    *((int*)elem) = INT_POISON_VAL;
    return true;
}
References INT_POISON_VAL.
Referenced by main().
int_str()
char * int_str (const void * elem) [inline]
Definition at line 24 of file main.cpp.
                                       {
    static const size_t MAX_INT_STR_LEN = 15;
    char* str = (char*)calloc(MAX_INT_STR_LEN, sizeof(char));
    if (str == nullptr) return nullptr;
    snprintf(str, MAX_INT_STR_LEN - 1, "%d", *((const int*)elem));
    return str;
}
Referenced by main().
int_verify()
bool int_verify (void * elem) [inline]
Definition at line 15 of file main.cpp.
                                   {
    if (elem == nullptr)
        return false;
    if (*((int*)elem) == INT_POISON_VAL)
        return false;
    return true;
}
References INT_POISON_VAL.
Referenced by main().
main()
int main ()
Definition at line 38 of file main.cpp.
           {
    log_open_file(&log_file, "wb");
    Tree tree = {};
    TREE_CTOR(&tree, sizeof(int), &int_dtor, &int_verify, &int_str);
    int push_val = 10;
    tree_insert_root(&tree, &push_val);
    TREE_DUMP(&tree);
    push_val = 30;
    tree_insert(&tree, &tree.root->right, tree.root, &push_val);
    TREE_DUMP(&tree);
    push_val = 20;
    tree_insert(&tree, &tree.root->left, tree.root, &push_val);
    TREE_DUMP(&tree);
    tree_delete(&tree, &tree.root->right, false);
    TREE_DUMP(&tree);
    tree_dtor(&tree);
    log_close_file(&log_file);
}
References int_dtor(), int_str(), int_verify(), TreeNode::left, log_close_file(), log_file, log_open_file(), TreeNode::right, Tree::root, TREE_CTOR, tree_delete(), tree_dtor(), TREE_DUMP, tree_insert(), and tree_insert_root().
Variable Documentation
INT_POISON_VAL
const int INT_POISON_VAL = __INT_MAX__ - 13
Definition at line 6 of file main.cpp.
Referenced by int_dtor(), and int_verify().
log_file
LogFileData log_file = {"log"}
Definition at line 4 of file main.cpp.
{"log"};
Referenced by log_close_file(), log_create_timestamp_dir(), log_open_file(), log_printf(), main(), tree_dump(), tree_dump_dot(), and tree_print_error().