releases/Tree/Tree.h File Reference
#include <stdlib.h>
#include <assert.h>
#include <stdarg.h>
#include utils/macros.h
Classes
struct TreeNode
Specifies tree node data.
struct Tree
Specifies tree data.
Macros
#define TREE_CTOR(tree, elem_size, dtor, verify, val_str) tree_ctor(tree, elem_size, dtor)
Tree constructor.
#define TREE_DUMP(tree) (void) 0
(Disabled) Tree dump
#define TREE_VERIFY(tree) Tree::OK
(Disabled) Tree verificator
#define TREE_VERIFY_NO_TRAVERSAL(tree) Tree::OK
(Disabled) No traversal Tree verificator
#define TREE_ASSERT(tree) Tree::OK
(Disabled) Tree assertion macros
#define TREE_ASSERT_NO_TRAVERSAL(tree) Tree::OK
(Disabled) No traversal Tree assertion macros
#define TREE_NODE_VERIFY(tree, node, depth) Tree::OK
(Disabled) Node verificator
#define TREE_NODE_ASSERT(tree, node, depth) Tree::OK
(Disabled) Node assertion function
#define TREE_OK(tree, res) (void) 0
(Disabled) Checks res and writes log if res is not OK
Typedefs
typedef bool Elem_t_func(void *elem)
Function template for elem_t destructor and verificator.
typedef char * Elem_t_val_str(const void *elem)
Function template for elem_t value string.
typedef TreeNodeActionRes() TreeNodeAction(Tree *tree, TreeNode **node, va_list *args, size_t depth, const TreeChildSide side)
Traversal action function template. Can receive arguments through va_list.
Enumerations
enum class TreeChildSide {
LEFT = -1
, ROOT = 0
, RIGHT = 1
, LEFT = -1
,
ROOT = 0
, RIGHT = 1
, LEFT = -1
, ROOT = 0
,
RIGHT = 1
 }
Indicates side of child node.
enum class TreeNodeActionRes {
EXIT_FULL = -2
, EXIT_NODE = -1
, ERR = 0
, OK = 1
,
EXIT_FULL = -2
, EXIT_NODE = -1
, ERR = 0
, OK = 1
,
EXIT_FULL = -2
, EXIT_NODE = -1
, ERR = 0
, OK = 1
 }
Traversal action function result.
Functions
int tree_ctor (Tree *tree, const size_t elem_size, Elem_t_func *elem_t_dtor)
(Use macros TREE_CTOR) Tree constructor
int tree_dtor (Tree *tree)
Tree destructor.
int tree_get_elem (Tree *tree, const TreeNode *node, void **dest)
Get element value from TreeNode.
int tree_set_elem (Tree *tree, TreeNode *node, void *src, bool dtor=true)
Set element value in TreeNode.
int tree_insert (Tree *tree, TreeNode **node, TreeNode *parent, void *elem)
Insert node in tree.
int tree_delete (Tree *tree, TreeNode **node, bool recursive=false)
Delete node from tree.
int tree_insert_root (Tree *tree, void *elem)
Insert to root.
int tree_traversal (Tree *tree, TreeNode **root, TreeNodeAction *actions[4],...)
Tree traversal function. Recieves TreeNodeAction functions and va_args for them.
int tree_preorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree preorder traversal function. Recieves TreeNodeAction function and va_args for it.
int tree_inorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree inorder traversal function. Recieves TreeNodeAction function and va_args for it.
int tree_postorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree postorder traversal function. Recieves TreeNodeAction function and va_args for it.
bool tree_node_is_initialised (const TreeNode *node)
Checks if TreeNode was initialised.
bool tree_is_initialised (const Tree *tree)
Checks if Tree was initialised.
Macro Definition Documentation
TREE_ASSERT
#define TREE_ASSERT(tree) Tree::OK
(Disabled) Tree assertion macros
Parameters
tree
Definition at line 449 of file Tree.h.
TREE_ASSERT_NO_TRAVERSAL
#define TREE_ASSERT_NO_TRAVERSAL(tree) Tree::OK
(Disabled) No traversal Tree assertion macros
Parameters
tree
Definition at line 456 of file Tree.h.
TREE_CTOR
#define TREE_CTOR(tree, elem_size, dtor, verify, val_str) tree_ctor(tree, elem_size, dtor)
Tree constructor.
Parameters
tree
elem_size sizeof(Elem_t)
dtor Elem_t destructor function
verify not needed (TREE_DEBUG)
val_str not needed (TREE_DEBUG)
Returns
int
Definition at line 417 of file Tree.h.
TREE_DUMP
#define TREE_DUMP(tree) (void) 0
(Disabled) Tree dump
Parameters
tree
Definition at line 424 of file Tree.h.
TREE_NODE_ASSERT
#define TREE_NODE_ASSERT(tree, node, depth) Tree::OK
(Disabled) Node assertion function
Parameters
tree
node
depth
Definition at line 476 of file Tree.h.
TREE_NODE_VERIFY
#define TREE_NODE_VERIFY(tree, node, depth) Tree::OK
(Disabled) Node verificator
Parameters
tree
node
depth
Returns
int
Definition at line 467 of file Tree.h.
TREE_OK
#define TREE_OK(tree, res) (void) 0
(Disabled) Checks res and writes log if res is not OK
Parameters
tree
res
Definition at line 484 of file Tree.h.
TREE_VERIFY
#define TREE_VERIFY(tree) Tree::OK
(Disabled) Tree verificator
Parameters
tree
Returns
int
Definition at line 433 of file Tree.h.
TREE_VERIFY_NO_TRAVERSAL
#define TREE_VERIFY_NO_TRAVERSAL(tree) Tree::OK
(Disabled) No traversal Tree verificator
Parameters
tree
Returns
int
Definition at line 442 of file Tree.h.
Typedef Documentation
Elem_t_func
typedef bool Elem_t_func(void *elem)
Function template for elem_t destructor and verificator.
Parameters
elem
Returns
bool
Definition at line 37 of file Tree.h.
Elem_t_val_str
typedef char * Elem_t_val_str(const void *elem)
Function template for elem_t value string.
Parameters
elem
Returns
char*
Definition at line 45 of file Tree.h.
TreeNodeAction
typedef TreeNodeActionRes() TreeNodeAction(Tree *tree, TreeNode **node, va_list *args, size_t depth, const TreeChildSide side)
Traversal action function template. Can receive arguments through va_list.
Parameters
tree
node
args
depth distance from root
side child side
Definition at line 107 of file Tree.h.
Enumeration Type Documentation
TreeChildSide
enum class TreeChildSide [strong]
Indicates side of child node.
Enumerator
LEFT
ROOT
RIGHT
LEFT
ROOT
RIGHT
LEFT
ROOT
RIGHT
Definition at line 15 of file Tree.h.
                         {
    LEFT = -1,
    ROOT = 0,
    RIGHT = 1,
};
TreeNodeActionRes
enum class TreeNodeActionRes [strong]
Traversal action function result.
Enumerator
EXIT_FULL
EXIT_NODE
ERR
OK
EXIT_FULL
EXIT_NODE
ERR
OK
EXIT_FULL
EXIT_NODE
ERR
OK
Definition at line 24 of file Tree.h.
                             {
    EXIT_FULL = -2,
    EXIT_NODE = -1,
    ERR = 0,
    OK = 1,
};
Function Documentation
tree_ctor()
int tree_ctor (Tree * tree, const size_t elem_size, Elem_t_func * elem_t_dtor)
(Use macros TREE_CTOR) Tree constructor
Parameters
tree
elem_size sizeof(Elem_t)
elem_t_dtor Elem_t destructor
Returns
int
Definition at line 51 of file tree.cpp.
                                                                            {
    assert(tree);
    assert(elem_size > 0);
    // elem_t_dtor can be nullptr
    int res = tree->OK;
    if (tree_is_initialised(tree)) {
        res |= tree->ALREADY_INITIALISED;
        TREE_OK(tree, res);
        return res;
    }
    tree->size = 0;
    tree->elem_size = elem_size;
    tree->node_elem_t_dtor = elem_t_dtor;
    res |= TREE_ASSERT(tree);
    return res;
}
References Tree::ALREADY_INITIALISED, Tree::elem_size, Tree::node_elem_t_dtor, Tree::OK, Tree::size, TREE_ASSERT, tree_is_initialised(), and TREE_OK.
tree_delete()
int tree_delete (Tree * tree, TreeNode ** node, bool recursive = false)
Delete node from tree.
Parameters
tree
node
recursive if true - deletes all children too
Returns
int
Definition at line 214 of file tree.cpp.
                                                             {
    int res = TREE_ASSERT(tree);
    if (*node == nullptr) {
        res |= Tree::INVALID_NODE_PTR;
        TREE_OK(tree, res);
        return res;
    }
    if (recursive)
        res |= tree_postorder(tree, node, &tree_delete_node_);
    else
        res |= tree_node_dtor_(tree, node);
    if (res != Tree::OK) {
        TREE_OK(tree, res);
        return res;
    }
    tree->size--;
    return res;
}
References Tree::INVALID_NODE_PTR, Tree::OK, Tree::size, TREE_ASSERT, TREE_OK, and tree_postorder().
Referenced by main().
tree_dtor()
int tree_dtor (Tree * tree)
Tree destructor.
Parameters
tree
Returns
int
Definition at line 72 of file tree.cpp.
                          {
    assert(tree);
    int res = TREE_ASSERT(tree);
    if (tree->root != nullptr) {
        res |= tree_delete(tree, &tree->root, true);
        if (res != Tree::OK)
            return res;
    }
    assert(tree->root == nullptr);
    tree->size = Tree::UNITIALISED_VAL;
    tree->elem_size = Tree::UNITIALISED_VAL;
    return res;
}
References Tree::elem_size, Tree::OK, Tree::root, Tree::size, TREE_ASSERT, tree_delete(), and Tree::UNITIALISED_VAL.
Referenced by main().
tree_get_elem()
int tree_get_elem (Tree * tree, const TreeNode * node, void ** dest)
Get element value from TreeNode.
Parameters
tree
node
dest
Returns
int
Definition at line 148 of file tree.cpp.
                                                                 {
    assert(tree);
    assert(dest);
    assert(*dest == nullptr);
    int res = TREE_NODE_ASSERT(tree, node, 0);
    *dest = node->elem;
    return res;
}
References TreeNode::elem, and TREE_NODE_ASSERT.
tree_inorder()
int tree_inorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree inorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action infix action
...
Returns
int
Definition at line 340 of file tree.cpp.
                                                                           {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {nullptr, action, nullptr, nullptr};
    bool exit = false;
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT, &exit);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
tree_insert()
int tree_insert (Tree * tree, TreeNode ** node, TreeNode * parent, void * elem)
Insert node in tree.
Parameters
tree
node destination pointer
parent
elem
Returns
int
Definition at line 180 of file tree.cpp.
                                                                           {
    assert(tree);
    assert(node);
    assert(elem);
    int res = TREE_ASSERT(tree);
    res |= tree_node_ctor_(node, elem, tree->elem_size, parent);
    if (res != Tree::OK) {
        TREE_OK(tree, res);
        return res;
    }
    tree->size++;
    res |= TREE_ASSERT(tree);
    return res;
}
References Tree::elem_size, Tree::OK, Tree::size, TREE_ASSERT, and TREE_OK.
Referenced by main(), and tree_insert_root().
tree_insert_root()
int tree_insert_root (Tree * tree, void * elem) [inline]
Insert to root.
Parameters
tree
elem
Returns
int
Definition at line 177 of file Tree.h.
                                                    {
    return tree_insert(tree, &tree->root, nullptr, elem);
}
References Tree::root, and tree_insert().
Referenced by main().
tree_is_initialised()
bool tree_is_initialised (const Tree * tree) [inline]
Checks if Tree was initialised.
Parameters
tree
Returns
true
false
Definition at line 243 of file Tree.h.
                                                  {
    return !(tree->size == tree->UNITIALISED_VAL && tree->root == nullptr &&
             tree->node_elem_t_dtor == nullptr);
}
References Tree::node_elem_t_dtor, Tree::root, Tree::size, and Tree::UNITIALISED_VAL.
Referenced by tree_ctor(), tree_dump(), and tree_verify().
tree_node_is_initialised()
bool tree_node_is_initialised (const TreeNode * node) [inline]
Checks if TreeNode was initialised.
Parameters
node
Returns
true
false
Definition at line 232 of file Tree.h.
                                                           {
    return !(node->elem == nullptr && node->left == nullptr && node->right == nullptr);
}
References TreeNode::elem, TreeNode::left, and TreeNode::right.
Referenced by tree_node_verify().
tree_postorder()
int tree_postorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree postorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action postfix action
...
Returns
int
Definition at line 364 of file tree.cpp.
                                                                             {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {nullptr, nullptr, action, nullptr};
    bool exit = false;
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT, &exit);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
tree_preorder()
int tree_preorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree preorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action prefix action
...
Returns
int
Definition at line 316 of file tree.cpp.
                                                                            {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {action, nullptr, nullptr, nullptr};
    bool exit = false;
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT, &exit);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
Referenced by tree_dump_dot().
tree_set_elem()
int tree_set_elem (Tree * tree, TreeNode * node, void * src, bool dtor = true)
Set element value in TreeNode.
Parameters
tree
node
src
dtor do dtor on old value?
Returns
int
Definition at line 160 of file tree.cpp.
                                                                    {
    assert(tree);
    assert(src);
    int res = TREE_NODE_ASSERT(tree, node, 0);
    if (dtor && tree->node_elem_t_dtor != nullptr) {
        if (!tree->node_elem_t_dtor(node->elem)) {
            res |= Tree::CANNOT_DELETE;
            TREE_OK(tree, res);
            return res;
        }
    }
    memcpy(node->elem, src, tree->elem_size);
    res |= TREE_NODE_ASSERT(tree, node, 0);
    return res;
}
References Tree::CANNOT_DELETE, TreeNode::elem, Tree::elem_size, Tree::node_elem_t_dtor, TREE_NODE_ASSERT, and TREE_OK.
tree_traversal()
int tree_traversal (Tree * tree, TreeNode ** root, TreeNodeAction * actions[4], ...)
Tree traversal function. Recieves TreeNodeAction functions and va_args for them.
Parameters
tree
root start point
actions {pre_action, in_action, post_action, null_action}
...
Returns
int
Definition at line 294 of file tree.cpp.
                                                                                 {
    assert(tree);
    assert(root);
    assert(actions);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, actions);
    bool exit = false;
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT, &exit);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
Referenced by tree_dump().