src/utils/text/text_lib.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>
Functions
size_t strncat_len (char *dest, const char *src, const ssize_t max_len)
Function Documentation
strncat_len()
size_t strncat_len (char * dest, const char * src, const ssize_t max_len)
Definition at line 3 of file text_lib.cpp.
                                                                       {
    assert(dest);
    assert(src);
    size_t dest_i = 0;
    while (dest[dest_i] && max_len - dest_i > 0)
        dest_i++;
    size_t src_i = 0;
    do {
        dest[dest_i] = src[src_i];
    } while (src[src_i++] && max_len - ++dest_i > 0);
    return dest_i;
}
Referenced by log_create_timestamp_dir(), log_open_file(), and tree_dump_dot().