src/tree.h File Reference
#include <stdlib.h>
#include <assert.h>
#include <stdarg.h>
#include "utils/macros.h"
Classes
struct TreeNode
Specifies tree node data.
struct Tree
Specifies tree data.
Macros
#define TREE_DEBUG
#define TREE_CTOR(tree, elem_size, dtor, verify, val_str)
Tree constructor.
#define TREE_DUMP(tree) tree_dump(tree, VAR_CODE_DATA(tree))
Tree dump.
#define TREE_OK(tree, res)
Checks res and writes log if res is not OK.
#define TREE_VERIFY(tree) tree_verify(tree)
Tree verificator.
#define TREE_VERIFY_NO_TRAVERSAL(tree) tree_verify(tree, false)
No traversal Tree verificator.
#define TREE_ASSERT(tree)
Tree assertion macros.
#define TREE_ASSERT_NO_TRAVERSAL(tree)
No traversal Tree assertion macros.
#define TREE_NODE_VERIFY(tree, node, depth) tree_node_verify(tree, node, depth)
Node verificator.
#define TREE_NODE_ASSERT(tree, node, depth)
Node assertion function.
Typedefs
typedef bool Elem_t_func(void *elem)
Function template for elem_t destructor and verificator.
typedef char * Elem_t_val_str(const void *elem)
Function template for elem_t value string.
typedef TreeNodeActionRes() TreeNodeAction(Tree *tree, TreeNode **node, va_list *args, size_t depth, const TreeChildSide side)
Traversal action function template. Can receive arguments through va_list.
Enumerations
enum class TreeChildSide { LEFT = -1
, ROOT = 0
, RIGHT = 1
 }
Indicates side of child node.
enum class TreeNodeActionRes { EXIT = -1
, ERROR = 0
, OK = 1
 }
Traversal action function result.
Functions
int tree_ctor (Tree *tree, const size_t elem_size, Elem_t_func *elem_t_dtor)
(Use macros TREE_CTOR) Tree constructor
int tree_dtor (Tree *tree)
Tree destructor.
int tree_insert (Tree *tree, TreeNode **node, TreeNode *parent, void *elem)
Insert node in tree.
int tree_delete (Tree *tree, TreeNode **node, bool recursive=false)
Delete node from tree.
int tree_insert_root (Tree *tree, void *elem)
Insert to root.
int tree_traversal (Tree *tree, TreeNode **root, TreeNodeAction *actions[4],...)
Tree traversal function. Recieves TreeNodeAction functions and va_args for them.
int tree_preorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree preorder traversal function. Recieves TreeNodeAction function and va_args for it.
int tree_inorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree inorder traversal function. Recieves TreeNodeAction function and va_args for it.
int tree_postorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree postorder traversal function. Recieves TreeNodeAction function and va_args for it.
bool tree_node_is_initialised (const TreeNode *node)
Checks if TreeNode was initialised.
bool tree_is_initialised (const Tree *tree)
Checks if Tree was initialised.
void tree_print_error (const int err_code)
Prints text error to log file.
int tree_verify (Tree *tree, bool do_traversal=true)
(Use TREE_VERIFY macros) Verifies Tree data
int tree_node_verify (const Tree *tree, const TreeNode *node, const size_t depth)
(Use TREE_NODE_VERIFY macros) Verifies TreeNode
int tree_ctor_debug (Tree *tree, const size_t elem_size, Elem_t_func *elem_t_dtor, Elem_t_func *elem_t_verify, Elem_t_val_str *elem_t_val_str, const VarCodeData var_data)
(Use TREE_CTOR macros) TREE_DEBUG mode constructor
void tree_dump (Tree *tree, const VarCodeData var_data)
(Use TREE_DUMP macros) Dumps tree to log file
bool tree_dump_dot (Tree *tree, char *img_filename)
Dumps tree to dot img file.
Macro Definition Documentation
TREE_ASSERT
#define TREE_ASSERT(tree)
Value:
                                TREE_VERIFY(tree); \
                                TREE_OK(tree, res); \
                                if (res != Tree::OK) \
                                    return res
Tree assertion macros.
Parameters
tree
Definition at line 343 of file tree.h.
TREE_ASSERT_NO_TRAVERSAL
#define TREE_ASSERT_NO_TRAVERSAL(tree)
Value:
                                TREE_VERIFY_NO_TRAVERSAL(tree); \
                                TREE_OK(tree, res); \
                                if (res != Tree::OK) \
                                    return res
No traversal Tree assertion macros.
Parameters
tree
Definition at line 353 of file tree.h.
TREE_CTOR
#define TREE_CTOR(tree, elem_size, dtor, verify, val_str)
Value:
                                                                              tree_ctor_debug(tree, elem_size, dtor, \
                                                                              verify, val_str, \
                                                                              VAR_CODE_DATA_PTR(tree))
Tree constructor.
Parameters
tree
elem_size sizeof(Elem_t)
dtor Elem_t destructor function
verify Elem_t verificator function
val_str Elem_t val_str functions
Returns
int
Definition at line 297 of file tree.h.
TREE_DEBUG
#define TREE_DEBUG
Definition at line 10 of file tree.h.
TREE_DUMP
#define TREE_DUMP(tree) tree_dump(tree, VAR_CODE_DATA(tree))
Tree dump.
Parameters
tree
Definition at line 305 of file tree.h.
TREE_NODE_ASSERT
#define TREE_NODE_ASSERT(tree, node, depth)
Value:
                                                TREE_NODE_VERIFY(tree, node, depth); \
                                                TREE_OK(tree, res); \
                                                if (res != Tree::OK) \
                                                    return res
Node assertion function.
Parameters
tree
node
depth
Definition at line 377 of file tree.h.
TREE_NODE_VERIFY
#define TREE_NODE_VERIFY(tree, node, depth) tree_node_verify(tree, node, depth)
Node verificator.
Parameters
tree
node
depth
Returns
int
Definition at line 368 of file tree.h.
TREE_OK
#define TREE_OK(tree, res)
Value:
                                    do { \
                                    if (res != tree->OK) { \
                                        tree_print_error(res); \
                                        TREE_DUMP(tree); \
                                    } \
                                } while (0)
Checks res and writes log if res is not OK.
Parameters
tree
res
Definition at line 313 of file tree.h.
                                   { \
                                    if (res != tree->OK) { \
                                        tree_print_error(res); \
                                        TREE_DUMP(tree); \
                                    } \
                                } while (0)
TREE_VERIFY
#define TREE_VERIFY(tree) tree_verify(tree)
Tree verificator.
Parameters
tree
Returns
int
Definition at line 327 of file tree.h.
TREE_VERIFY_NO_TRAVERSAL
#define TREE_VERIFY_NO_TRAVERSAL(tree) tree_verify(tree, false)
No traversal Tree verificator.
Parameters
tree
Returns
int
Definition at line 336 of file tree.h.
Typedef Documentation
Elem_t_func
typedef bool Elem_t_func(void *elem)
Function template for elem_t destructor and verificator.
Parameters
elem
Returns
bool
Definition at line 36 of file tree.h.
Elem_t_val_str
typedef char * Elem_t_val_str(const void *elem)
Function template for elem_t value string.
Parameters
elem
Returns
char*
Definition at line 44 of file tree.h.
TreeNodeAction
typedef TreeNodeActionRes() TreeNodeAction(Tree *tree, TreeNode **node, va_list *args, size_t depth, const TreeChildSide side)
Traversal action function template. Can receive arguments through va_list.
Parameters
tree
node
args
depth distance from root
side child side
Definition at line 106 of file tree.h.
Enumeration Type Documentation
TreeChildSide
enum class TreeChildSide [strong]
Indicates side of child node.
Enumerator
LEFT
ROOT
RIGHT
Definition at line 15 of file tree.h.
                         {
    LEFT = -1,
    ROOT = 0,
    RIGHT = 1,
};
TreeNodeActionRes
enum class TreeNodeActionRes [strong]
Traversal action function result.
Enumerator
EXIT
ERROR
OK
Definition at line 24 of file tree.h.
                             {
    EXIT = -1,
    ERROR = 0,
    OK = 1,
};
Function Documentation
tree_ctor()
int tree_ctor (Tree * tree, const size_t elem_size, Elem_t_func * elem_t_dtor)
(Use macros TREE_CTOR) Tree constructor
Parameters
tree
elem_size sizeof(Elem_t)
elem_t_dtor Elem_t destructor
Returns
int
Definition at line 50 of file tree.cpp.
                                                                            {
    assert(tree);
    assert(elem_size > 0);
    // elem_t_dtor can be nullptr
    int res = tree->OK;
    if (tree_is_initialised(tree)) {
        res |= tree->ALREADY_INITIALISED;
        TREE_OK(tree, res);
        return res;
    }
    tree->size = 0;
    tree->elem_size = elem_size;
    tree->node_elem_t_dtor = elem_t_dtor;
    res |= TREE_ASSERT(tree);
    return res;
}
References Tree::ALREADY_INITIALISED, Tree::elem_size, Tree::node_elem_t_dtor, Tree::OK, Tree::size, TREE_ASSERT, tree_is_initialised(), and TREE_OK.
Referenced by tree_ctor_debug().
tree_ctor_debug()
int tree_ctor_debug (Tree * tree, const size_t elem_size, Elem_t_func * elem_t_dtor, Elem_t_func * elem_t_verify, Elem_t_val_str * elem_t_val_str, const VarCodeData var_data)
(Use TREE_CTOR macros) TREE_DEBUG mode constructor
Parameters
tree
elem_size
elem_t_dtor
elem_t_verify
elem_t_val_str
var_data
Returns
int
Definition at line 409 of file tree.cpp.
                                                                                {
    assert(tree);
    tree->var_data = var_data;
    tree->node_elem_t_verify = elem_t_verify;
    tree->node_elem_t_val_str = elem_t_val_str;
    return tree_ctor(tree, elem_size, elem_t_dtor);
}
References Tree::node_elem_t_val_str, Tree::node_elem_t_verify, tree_ctor(), and Tree::var_data.
tree_delete()
int tree_delete (Tree * tree, TreeNode ** node, bool recursive = false)
Delete node from tree.
Parameters
tree
node
recursive if true - deletes all children too
Returns
int
Definition at line 179 of file tree.cpp.
                                                             {
    int res = TREE_ASSERT(tree);
    if (*node == nullptr) {
        res |= Tree::INVALID_NODE_PTR;
        TREE_OK(tree, res);
        return res;
    }
    if (recursive)
        res |= tree_postorder(tree, node, &tree_delete_node_);
    else
        res |= tree_node_dtor_(tree, node);
    if (res != Tree::OK) {
        TREE_OK(tree, res);
        return res;
    }
    tree->size--;
    return res;
}
References Tree::INVALID_NODE_PTR, Tree::OK, Tree::size, TREE_ASSERT, TREE_OK, and tree_postorder().
Referenced by main(), and tree_dtor().
tree_dtor()
int tree_dtor (Tree * tree)
Tree destructor.
Parameters
tree
Returns
int
Definition at line 71 of file tree.cpp.
                          {
    assert(tree);
    int res = TREE_ASSERT(tree);
    res |= tree_delete(tree, &tree->root, true);
    if (res != Tree::OK)
        return res;
    assert(tree->root == nullptr);
    tree->size = Tree::UNITIALISED_VAL;
    tree->elem_size = Tree::UNITIALISED_VAL;
    return res;
}
References Tree::elem_size, Tree::OK, Tree::root, Tree::size, TREE_ASSERT, tree_delete(), and Tree::UNITIALISED_VAL.
Referenced by main().
tree_dump()
void tree_dump (Tree * tree, const VarCodeData var_data)
(Use TREE_DUMP macros) Dumps tree to log file
Parameters
tree
var_data
Definition at line 162 of file dump.cpp.
                                                        {
    assert(tree);
    LOG_(HTML_BEGIN);
    LOG_(" tree_dump() called from %s:%d %s\n"
         " %s[%p] initialised in %s:%d %s \n",
         call_data.file, call_data.line, call_data.func,
         tree->var_data.name, tree,
         tree->var_data.file, tree->var_data.line, tree->var_data.func);
    LOG_(" {\n");
    LOG_(" size = %zd\n", tree->size);
    LOG_(" root = %p\n", tree->root);
    LOG_(" {\n");
    if (!is_ptr_valid(tree->root)) {
        if (tree->size != 0 && tree_is_initialised(tree))
            LOG_(HTML_RED(" can't read (invalid pointer)\n"));
        LOG_(" }\n"
             " }\n" HTML_END);
        return;
    }
    LOG_(" "" prefix: ");
    TreeNodeAction* pre_actions[4] = {&tree_dump_log_open_node_val, nullptr,
                                      &tree_dump_log_close_node, &tree_dump_log_nil};
    tree_traversal(tree, &tree->root, pre_actions);
    LOG_("\n");
    LOG_(" "" infix: ");
    TreeNodeAction* in_actions[4] = {&tree_dump_log_open_node, &tree_dump_log_val,
                                     &tree_dump_log_close_node, &tree_dump_log_nil};
    tree_traversal(tree, &tree->root, in_actions);
    LOG_("\n");
    LOG_(" "" postfix: ");
    TreeNodeAction* post_actions[4] = {&tree_dump_log_open_node, nullptr,
                                       &tree_dump_log_close_node_val, &tree_dump_log_nil};
    tree_traversal(tree, &tree->root, post_actions);
    LOG_("\n");
    LOG_(" }\n"
         " }\n" HTML_END);
    char img_filename[log_file.MAX_FILENAME_LEN] = {};
    tree_dump_dot(tree, img_filename);
    LOG_("<img src=\"../../%s\">\n", img_filename);
}
References VarCodeData::file, VarCodeData::func, HTML_BEGIN, HTML_END, HTML_RED, is_ptr_valid(), VarCodeData::line, LOG_, log_file, LogFileData::MAX_FILENAME_LEN, VarCodeData::name, Tree::root, Tree::size, tree_dump_dot(), tree_is_initialised(), tree_traversal(), and Tree::var_data.
tree_dump_dot()
bool tree_dump_dot (Tree * tree, char * img_filename)
Dumps tree to dot img file.
Parameters
tree
img_filename
Returns
true
false
Definition at line 285 of file dump.cpp.
                                                   {
    assert(tree);
    assert(img_filename);
    static size_t dot_number = 0;
    char dot_filename[log_file.MAX_FILENAME_LEN] = {};
    size_t str_len = strncat_len(dot_filename, log_file.timestamp_dir, log_file.MAX_FILENAME_LEN);
    snprintf(dot_filename + str_len, log_file.MAX_FILENAME_LEN - str_len,
             "%zd", dot_number);
    str_len = strncat_len(dot_filename, ".dot", log_file.MAX_FILENAME_LEN);
    FILE* file = fopen(dot_filename, "wb");
    if (file == nullptr)
        return false;
    FPRINTF_("digraph List{\n"
             " graph [bgcolor=" BACKGROUND_COLOR "];\n"
             " node[color=white, fontcolor=" FONT_COLOR ", fontsize=14, "
             "fontname=\"verdana\", style=\"filled\", fillcolor=\"#6e7681\"];\n\n");
    tree_preorder(tree, &tree->root, &tree_dump_dot_log_node_, file);
    FPRINTF_("}\n");
    if (fclose(file) != 0) {
        perror("Error closing file");
        return false;
    }
    str_len = strncat_len(img_filename, log_file.timestamp_dir, log_file.MAX_FILENAME_LEN);
    snprintf(img_filename + str_len, log_file.MAX_FILENAME_LEN - str_len, "%zd", dot_number++);
    str_len = strncat_len(img_filename, ".svg", log_file.MAX_FILENAME_LEN);
    if (!create_img(dot_filename, img_filename)) {
        fprintf(stderr, "Error creating dot graph\n");
        return false;
    }
    return true;
}
References BACKGROUND_COLOR, create_img(), FONT_COLOR, FPRINTF_, log_file, LogFileData::MAX_FILENAME_LEN, Tree::root, strncat_len(), LogFileData::timestamp_dir, and tree_preorder().
Referenced by tree_dump().
tree_inorder()
int tree_inorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree inorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action infix action
...
Returns
int
Definition at line 296 of file tree.cpp.
                                                                           {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {nullptr, action, nullptr, nullptr};
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
tree_insert()
int tree_insert (Tree * tree, TreeNode ** node, TreeNode * parent, void * elem)
Insert node in tree.
Parameters
tree
node destination pointer
parent
elem
Returns
int
Definition at line 145 of file tree.cpp.
                                                                           {
    assert(tree);
    assert(node);
    assert(elem);
    int res = TREE_ASSERT(tree);
    res |= tree_node_ctor_(node, elem, tree->elem_size, parent);
    if (res != Tree::OK) {
        TREE_OK(tree, res);
        return res;
    }
    tree->size++;
    res |= TREE_ASSERT(tree);
    return res;
}
References Tree::elem_size, Tree::OK, Tree::size, TREE_ASSERT, and TREE_OK.
Referenced by main(), and tree_insert_root().
tree_insert_root()
int tree_insert_root (Tree * tree, void * elem) [inline]
Insert to root.
Parameters
tree
elem
Returns
int
Definition at line 155 of file tree.h.
                                                    {
    return tree_insert(tree, &tree->root, nullptr, elem);
}
References Tree::root, and tree_insert().
Referenced by main().
tree_is_initialised()
bool tree_is_initialised (const Tree * tree) [inline]
Checks if Tree was initialised.
Parameters
tree
Returns
true
false
Definition at line 221 of file tree.h.
                                                  {
    return !(tree->size == tree->UNITIALISED_VAL && tree->root == nullptr &&
             tree->node_elem_t_dtor == nullptr);
}
References Tree::node_elem_t_dtor, Tree::root, Tree::size, and Tree::UNITIALISED_VAL.
Referenced by tree_ctor(), tree_dump(), and tree_verify().
tree_node_is_initialised()
bool tree_node_is_initialised (const TreeNode * node) [inline]
Checks if TreeNode was initialised.
Parameters
node
Returns
true
false
Definition at line 210 of file tree.h.
                                                           {
    return !(node->elem == nullptr && node->left == nullptr && node->right == nullptr);
}
References TreeNode::elem, TreeNode::left, and TreeNode::right.
Referenced by tree_node_verify().
tree_node_verify()
int tree_node_verify (const Tree * tree, const TreeNode * node, const size_t depth)
(Use TREE_NODE_VERIFY macros) Verifies TreeNode
Parameters
tree
node
depth
Returns
int
Definition at line 386 of file tree.cpp.
                                                                                 {
    assert(tree);
    assert(node);
    int res = tree->OK;
    if (!tree_node_is_initialised(node)) {
        res |= tree->UNITIALISED;
        return res;
    }
    CHECK_ERR_(node != tree->root && (node->parent == nullptr ||
               !(node->parent->left == node || node->parent->right == node)), tree->DAMAGED_PATH);
    CHECK_ERR_((ssize_t)depth > tree->size, tree->DAMAGED_PATH);
    if (tree->node_elem_t_verify != nullptr)
        CHECK_ERR_(!tree->node_elem_t_verify(node->elem), tree->NODE_VERIFY_FAIL);
    return res;
}
References CHECK_ERR_, Tree::DAMAGED_PATH, TreeNode::elem, TreeNode::left, Tree::node_elem_t_verify, Tree::NODE_VERIFY_FAIL, Tree::OK, TreeNode::parent, TreeNode::right, Tree::root, Tree::size, tree_node_is_initialised(), and Tree::UNITIALISED.
tree_postorder()
int tree_postorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree postorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action postfix action
...
Returns
int
Definition at line 319 of file tree.cpp.
                                                                             {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {nullptr, nullptr, action, nullptr};
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
Referenced by tree_delete().
tree_preorder()
int tree_preorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree preorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action prefix action
...
Returns
int
Definition at line 273 of file tree.cpp.
                                                                            {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {action, nullptr, nullptr, nullptr};
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
Referenced by tree_dump_dot(), and tree_verify().
tree_print_error()
void tree_print_error (const int err_code)
Prints text error to log file.
Parameters
err_code
Definition at line 332 of file dump.cpp.
                                          {
    if (err_code == Tree::OK) {
        log_printf(&log_file, HTML_TEXT(HTML_GREEN("No error\n")));
    } else {
        PRINT_ERR_(ALLOC_ERR, "Can't allocate memory");
        PRINT_ERR_(ALREADY_INITIALISED, "Constructor called for already initialised or corrupted tree");
        PRINT_ERR_(UNITIALISED, "Tree is not initialised");
        PRINT_ERR_(INVALID_NODE_PTR, "TreeNode pointer is not valid for writing");
        PRINT_ERR_(POISON_VAL_FOUND, "There is poison value in TreeNode");
        PRINT_ERR_(INVALID_SIZE, "Actual tree size doesn't equal tree.size");
        PRINT_ERR_(NEGATIVE_SIZE, "Negative tree.size");
        PRINT_ERR_(DAMAGED_PATH, "Tree is damaged. Invalid path");
        PRINT_ERR_(ACTION_ERROR, "Some action on TreeNode failed");
        PRINT_ERR_(NODE_ALREADY_EXISTS, "Insertion is not allowed. Node already exists here");
        PRINT_ERR_(CANNOT_DELETE, "Cannot delete element. It has child/children");
        PRINT_ERR_(NODE_VERIFY_FAIL, "Node elem verification failed");
        PRINT_ERR_(INVALID_ELEM_T_SIZE, "tree.elem_size is <= 0");
    }
}
References HTML_GREEN, HTML_TEXT, log_file, log_printf(), Tree::OK, and PRINT_ERR_.
tree_traversal()
int tree_traversal (Tree * tree, TreeNode ** root, TreeNodeAction * actions[4], ...)
Tree traversal function. Recieves TreeNodeAction functions and va_args for them.
Parameters
tree
root start point
actions {pre_action, in_action, post_action, null_action}
...
Returns
int
Definition at line 252 of file tree.cpp.
                                                                                 {
    assert(tree);
    assert(root);
    assert(actions);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, actions);
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
Referenced by tree_dump().
tree_verify()
int tree_verify (Tree * tree, bool do_traversal = true)
(Use TREE_VERIFY macros) Verifies Tree data
Parameters
tree
do_traversal if true, will do traversal and verify each node
Returns
int
Definition at line 364 of file tree.cpp.
                                               {
    assert(tree);
    int res = Tree::OK;
    if (!tree_is_initialised(tree)) {
        res |= Tree::UNITIALISED;
        return res;
    }
    CHECK_ERR_(tree->elem_size <= 0, tree->INVALID_ELEM_T_SIZE);
    CHECK_ERR_(tree->size < 0, tree->NEGATIVE_SIZE);
    if (do_traversal) {
        size_t cnt = 0;
        res |= tree_preorder(tree, &tree->root, &tree_node_count_, &cnt);
        CHECK_ERR_(res != tree->ACTION_ERROR && (ssize_t)cnt != tree->size, tree->INVALID_SIZE);
    }
    return res;
}
References Tree::ACTION_ERROR, CHECK_ERR_, Tree::elem_size, Tree::INVALID_ELEM_T_SIZE, Tree::INVALID_SIZE, Tree::NEGATIVE_SIZE, Tree::OK, Tree::root, Tree::size, tree_is_initialised(), tree_preorder(), and Tree::UNITIALISED.