src/tree.cpp File Reference
#include "tree.h"
Macros
#define DO_ACTION_(action_)
#define CHECK_ERR_(clause, err) if (clause) res |= err
Functions
int tree_ctor (Tree *tree, const size_t elem_size, Elem_t_func *elem_t_dtor)
(Use macros TREE_CTOR) Tree constructor
int tree_dtor (Tree *tree)
Tree destructor.
int tree_node_ctor (TreeNode **node, void *elem, size_t elem_size, TreeNode *parent)
Node constructor.
int tree_node_dtor (Tree *tree, TreeNode **node)
Node destructor.
int tree_get_elem (Tree *tree, const TreeNode *node, void **dest)
Get element value from TreeNode.
int tree_set_elem (Tree *tree, TreeNode *node, void *src, bool dtor)
Set element value in TreeNode.
int tree_insert (Tree *tree, TreeNode **node, TreeNode *parent, void *elem)
Insert node in tree.
int tree_delete (Tree *tree, TreeNode **node, bool recursive)
Delete node from tree.
int tree_traversal (Tree *tree, TreeNode **root, TreeNodeAction *actions[4],...)
Tree traversal function. Recieves TreeNodeAction functions and va_args for them.
int tree_preorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree preorder traversal function. Recieves TreeNodeAction function and va_args for it.
int tree_inorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree inorder traversal function. Recieves TreeNodeAction function and va_args for it.
int tree_postorder (Tree *tree, TreeNode **root, TreeNodeAction *action,...)
Tree postorder traversal function. Recieves TreeNodeAction function and va_args for it.
int tree_verify (Tree *tree, bool do_traversal)
(Use TREE_VERIFY macros) Verifies Tree data
int tree_node_verify (const Tree *tree, const TreeNode *node, const size_t depth)
(Use TREE_NODE_VERIFY macros) Verifies TreeNode
int tree_ctor_debug (Tree *tree, const size_t elem_size, Elem_t_func *elem_t_dtor, Elem_t_func *elem_t_verify, Elem_t_val_str *elem_t_val_str, const VarCodeData var_data)
(Use TREE_CTOR macros) TREE_DEBUG mode constructor
Macro Definition Documentation
CHECK_ERR_
#define CHECK_ERR_(clause, err) if (clause) res |= err
Definition at line 392 of file tree.cpp.
Referenced by tree_node_verify(), and tree_verify().
DO_ACTION_
#define DO_ACTION_(action_)
Value:
                                do { \
                                if (*exit) return res; \
                                                                                                        \
                                if (action_ == nullptr) continue; \
                                                                                                        \
                                TreeNodeActionRes action_res = action_(tree, node, args, depth, side); \
                                if (action_res == TreeNodeActionRes::ERR) { \
                                    res |= Tree::ACTION_ERROR; \
                                    return res; \
                                } \
                                                                                                        \
                                if (action_res == TreeNodeActionRes::EXIT_FULL) { \
                                    *exit = true; \
                                    return res; \
                                } \
                                                                                                        \
                                if (action_res == TreeNodeActionRes::EXIT_NODE) return res; \
                            } while (0)
Definition at line 222 of file tree.cpp.
#define DO_ACTION_(action_) do { \
                                if (*exit) return res; \
                                                                                                        \
                                if (action_ == nullptr) continue; \
                                                                                                        \
                                TreeNodeActionRes action_res = action_(tree, node, args, depth, side); \
                                if (action_res == TreeNodeActionRes::ERR) { \
                                    res |= Tree::ACTION_ERROR; \
                                    return res; \
                                } \
                                                                                                        \
                                if (action_res == TreeNodeActionRes::EXIT_FULL) { \
                                    *exit = true; \
                                    return res; \
                                } \
                                                                                                        \
                                if (action_res == TreeNodeActionRes::EXIT_NODE) return res; \
                            } while (0)
Function Documentation
tree_ctor()
int tree_ctor (Tree * tree, const size_t elem_size, Elem_t_func * elem_t_dtor)
(Use macros TREE_CTOR) Tree constructor
Parameters
tree
elem_size sizeof(Elem_t)
elem_t_dtor Elem_t destructor
Returns
int
Definition at line 31 of file tree.cpp.
                                                                            {
    assert(tree);
    assert(elem_size > 0);
    // elem_t_dtor can be nullptr
    int res = tree->OK;
    if (tree_is_initialised(tree)) {
        res |= tree->ALREADY_INITIALISED;
        TREE_OK(tree, res);
        return res;
    }
    tree->size = 0;
    tree->elem_size = (ssize_t)elem_size;
    tree->node_elem_t_dtor = elem_t_dtor;
    res |= TREE_ASSERT(tree);
    return res;
}
References Tree::ALREADY_INITIALISED, Tree::elem_size, Tree::node_elem_t_dtor, Tree::OK, Tree::size, TREE_ASSERT, tree_is_initialised(), and TREE_OK.
Referenced by tree_ctor_debug().
tree_ctor_debug()
int tree_ctor_debug (Tree * tree, const size_t elem_size, Elem_t_func * elem_t_dtor, Elem_t_func * elem_t_verify, Elem_t_val_str * elem_t_val_str, const VarCodeData var_data)
(Use TREE_CTOR macros) TREE_DEBUG mode constructor
Parameters
tree
elem_size
elem_t_dtor
elem_t_verify
elem_t_val_str
var_data
Returns
int
Definition at line 439 of file tree.cpp.
                                                                                {
    assert(tree);
    tree->var_data = var_data;
    tree->node_elem_t_verify = elem_t_verify;
    tree->node_elem_t_val_str = elem_t_val_str;
    return tree_ctor(tree, elem_size, elem_t_dtor);
}
References Tree::node_elem_t_val_str, Tree::node_elem_t_verify, tree_ctor(), and Tree::var_data.
tree_delete()
int tree_delete (Tree * tree, TreeNode ** node, bool recursive = false)
Delete node from tree.
Parameters
tree
node
recursive if true - deletes all children too
Returns
int
Definition at line 198 of file tree.cpp.
                                                             {
    int res = TREE_ASSERT(tree);
    if (*node == nullptr) {
        res |= Tree::INVALID_NODE_PTR;
        TREE_OK(tree, res);
        return res;
    }
    if (recursive) {
        res |= tree_postorder(tree, node, &tree_delete_node_);
    } else {
        res |= tree_node_dtor(tree, node);
        tree->size--;
    }
    if (res != Tree::OK) {
        TREE_OK(tree, res);
        return res;
    }
    return res;
}
References Tree::INVALID_NODE_PTR, Tree::OK, Tree::size, TREE_ASSERT, tree_node_dtor(), TREE_OK, and tree_postorder().
Referenced by main(), and tree_dtor().
tree_dtor()
int tree_dtor (Tree * tree)
Tree destructor.
Parameters
tree
Returns
int
Definition at line 52 of file tree.cpp.
                          {
    assert(tree);
    int res = TREE_ASSERT(tree);
    if (tree->root != nullptr) {
        res |= tree_delete(tree, &tree->root, true);
        if (res != Tree::OK)
            return res;
    }
    assert(tree->root == nullptr);
    tree->node_elem_t_dtor = nullptr;
    tree->size = Tree::UNITIALISED_VAL;
    tree->elem_size = Tree::UNITIALISED_VAL;
    return res;
}
References Tree::elem_size, Tree::node_elem_t_dtor, Tree::OK, Tree::root, Tree::size, TREE_ASSERT, tree_delete(), and Tree::UNITIALISED_VAL.
Referenced by main().
tree_get_elem()
int tree_get_elem (Tree * tree, const TreeNode * node, void ** dest)
Get element value from TreeNode.
Parameters
tree
node
dest
Returns
int
Definition at line 129 of file tree.cpp.
                                                                 {
    assert(tree); (void) tree;
    assert(dest);
    assert(*dest == nullptr);
    int res = TREE_NODE_ASSERT(tree, node, 0);
    *dest = node->elem;
    return res;
}
References TreeNode::elem, and TREE_NODE_ASSERT.
tree_inorder()
int tree_inorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree inorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action infix action
...
Returns
int
Definition at line 324 of file tree.cpp.
                                                                           {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {nullptr, action, nullptr, nullptr};
    bool exit = false;
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT, &exit);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
tree_insert()
int tree_insert (Tree * tree, TreeNode ** node, TreeNode * parent, void * elem)
Insert node in tree.
Parameters
tree
node destination pointer
parent
elem
Returns
int
Definition at line 162 of file tree.cpp.
                                                                           {
    assert(tree);
    assert(node);
    assert(elem);
    int res = TREE_ASSERT(tree);
    res |= tree_node_ctor(node, elem, (size_t)tree->elem_size, parent);
    if (res != Tree::OK) {
        TREE_OK(tree, res);
        return res;
    }
    tree->size++;
    res |= TREE_ASSERT(tree);
    return res;
}
References Tree::elem_size, Tree::OK, Tree::size, TREE_ASSERT, tree_node_ctor(), and TREE_OK.
Referenced by main(), and tree_insert_root().
tree_node_ctor()
int tree_node_ctor (TreeNode ** node, void * elem, size_t elem_size, TreeNode * parent)
Node constructor.
Parameters
node
elem
elem_size
parent
Returns
int
Definition at line 72 of file tree.cpp.
                                                                                    {
    assert(node);
    assert(elem);
    assert(elem_size > 0);
    int res = Tree::OK;
    if (*node != nullptr) {
        res |= Tree::ALREADY_INITIALISED;
        return res;
    }
    *node = (TreeNode*)calloc(1, sizeof(TreeNode) + elem_size);
    if (*node == nullptr) {
        res |= Tree::ALLOC_ERR;
        return res;
    }
    (*node)->elem = (char*)(*node) + sizeof(TreeNode);
    memcpy((*node)->elem, elem, elem_size);
    (*node)->parent = parent;
    return res;
}
References Tree::ALLOC_ERR, Tree::ALREADY_INITIALISED, TreeNode::elem, and Tree::OK.
Referenced by tree_insert().
tree_node_dtor()
int tree_node_dtor (Tree * tree, TreeNode ** node)
Node destructor.
Parameters
tree
node
Returns
int
Definition at line 99 of file tree.cpp.
                                                {
    assert(tree);
    assert(node);
    int res = Tree::OK;
    if (*node == nullptr) {
        res |= Tree::INVALID_NODE_PTR;
        return res;
    }
    if ((*node)->left != nullptr || (*node)->right != nullptr) {
        res |= Tree::CANNOT_DELETE;
        return res;
    }
    if (tree->node_elem_t_dtor != nullptr) {
        if (!tree->node_elem_t_dtor((*node)->elem)) {
            res |= Tree::CANNOT_DELETE;
            return res;
        }
    }
    (*node)->parent = nullptr;
    FREE(*node);
    return res;
}
References Tree::CANNOT_DELETE, FREE, Tree::INVALID_NODE_PTR, Tree::node_elem_t_dtor, and Tree::OK.
Referenced by tree_delete().
tree_node_verify()
int tree_node_verify (const Tree * tree, const TreeNode * node, const size_t depth)
(Use TREE_NODE_VERIFY macros) Verifies TreeNode
Parameters
tree
node
depth
Returns
int
Definition at line 416 of file tree.cpp.
                                                                                 {
    assert(tree);
    assert(node);
    int res = tree->OK;
    if (!tree_node_is_initialised(node)) {
        res |= tree->UNITIALISED;
        return res;
    }
    CHECK_ERR_(node != tree->root && (node->parent == nullptr ||
               !(node->parent->left == node || node->parent->right == node)), tree->DAMAGED_PATH);
    CHECK_ERR_((ssize_t)depth > tree->size, tree->DAMAGED_PATH);
    if (tree->node_elem_t_verify != nullptr)
        CHECK_ERR_(!tree->node_elem_t_verify(node->elem), tree->NODE_VERIFY_FAIL);
    return res;
}
References CHECK_ERR_, Tree::DAMAGED_PATH, TreeNode::elem, TreeNode::left, Tree::node_elem_t_verify, Tree::NODE_VERIFY_FAIL, Tree::OK, TreeNode::parent, TreeNode::right, Tree::root, Tree::size, tree_node_is_initialised(), and Tree::UNITIALISED.
tree_postorder()
int tree_postorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree postorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action postfix action
...
Returns
int
Definition at line 348 of file tree.cpp.
                                                                             {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {nullptr, nullptr, action, nullptr};
    bool exit = false;
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT, &exit);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
Referenced by tree_delete().
tree_preorder()
int tree_preorder (Tree * tree, TreeNode ** root, TreeNodeAction * action, ...)
Tree preorder traversal function. Recieves TreeNodeAction function and va_args for it.
Parameters
tree
root start point
action prefix action
...
Returns
int
Definition at line 300 of file tree.cpp.
                                                                            {
    assert(tree);
    assert(root);
    assert(action);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, action);
    TreeNodeAction* actions[4] = {action, nullptr, nullptr, nullptr};
    bool exit = false;
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT, &exit);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
Referenced by tree_dump_dot(), and tree_verify().
tree_set_elem()
int tree_set_elem (Tree * tree, TreeNode * node, void * src, bool dtor = true)
Set element value in TreeNode.
Parameters
tree
node
src
dtor do dtor on old value?
Returns
int
Definition at line 141 of file tree.cpp.
                                                                    {
    assert(tree);
    assert(src);
    int res = TREE_NODE_ASSERT(tree, node, 0);
    if (dtor && tree->node_elem_t_dtor != nullptr) {
        if (!tree->node_elem_t_dtor(node->elem)) {
            res |= Tree::CANNOT_DELETE;
            TREE_OK(tree, res);
            return res;
        }
    }
    assert(tree->elem_size > 0);
    memcpy(node->elem, src, (size_t)tree->elem_size);
    res |= TREE_NODE_ASSERT(tree, node, 0);
    return res;
}
References Tree::CANNOT_DELETE, TreeNode::elem, Tree::elem_size, Tree::node_elem_t_dtor, TREE_NODE_ASSERT, and TREE_OK.
tree_traversal()
int tree_traversal (Tree * tree, TreeNode ** root, TreeNodeAction * actions[4], ...)
Tree traversal function. Recieves TreeNodeAction functions and va_args for them.
Parameters
tree
root start point
actions {pre_action, in_action, post_action, null_action}
...
Returns
int
Definition at line 278 of file tree.cpp.
                                                                                 {
    assert(tree);
    assert(root);
    assert(actions);
    int res = TREE_ASSERT_NO_TRAVERSAL(tree);
    va_list args = {};
    va_start(args, actions);
    bool exit = false;
    res |= tree_traversal_(tree, root, &args, actions, 0, TreeChildSide::ROOT, &exit);
    va_end(args);
    if (res != Tree::OK)
        return res;
    res |= TREE_ASSERT_NO_TRAVERSAL(tree);
    return res;
}
References Tree::OK, ROOT, and TREE_ASSERT_NO_TRAVERSAL.
Referenced by tree_dump().
tree_verify()
int tree_verify (Tree * tree, bool do_traversal = true)
(Use TREE_VERIFY macros) Verifies Tree data
Parameters
tree
do_traversal if true, will do traversal and verify each node
Returns
int
Definition at line 394 of file tree.cpp.
                                               {
    assert(tree);
    int res = Tree::OK;
    if (!tree_is_initialised(tree)) {
        res |= Tree::UNITIALISED;
        return res;
    }
    CHECK_ERR_(tree->elem_size <= 0, tree->INVALID_ELEM_T_SIZE);
    CHECK_ERR_(tree->size < 0, tree->NEGATIVE_SIZE);
    if (do_traversal) {
        size_t cnt = 0;
        res |= tree_preorder(tree, &tree->root, &tree_node_count_, &cnt);
        CHECK_ERR_(res != tree->ACTION_ERROR && (ssize_t)cnt != tree->size, tree->INVALID_SIZE);
    }
    return res;
}
References Tree::ACTION_ERROR, CHECK_ERR_, Tree::elem_size, Tree::INVALID_ELEM_T_SIZE, Tree::INVALID_SIZE, Tree::NEGATIVE_SIZE, Tree::OK, Tree::root, Tree::size, tree_is_initialised(), tree_preorder(), and Tree::UNITIALISED.